# Generated by Django 3.0.5 on 2020-05-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbooks',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
