# Generated by Django 3.0.5 on 2020-05-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200504_2037'),
        ('students', '0002_issuedbooks_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbooks',
            name='student',
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='issued_book',
            field=models.ManyToManyField(related_name='issue', to='books.Books'),
        ),
    ]
