# Generated by Django 3.0.5 on 2020-05-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200504_2037'),
        ('students', '0003_auto_20200511_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbooks',
            name='name',
        ),
        migrations.AddField(
            model_name='issuedbooks',
            name='student',
            field=models.ManyToManyField(related_name='Student_r', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='issued_book',
            field=models.ManyToManyField(related_name='issuedbook', to='books.Books'),
        ),
    ]
